### ISSUE TITLE
Toevoegen Decimal aan primaire types in MIM

### ISSUE THREAD

**Issue by lennartvanbergen-kadaster** [Geonovum/MIM-Werkomgeving#3]
Spin-off van NEN3610/Imvertor controle slag. Uit het document:
_--
20180723_VoorstellenImvertor-NEN3610KAD.docx

Voorstel 9.	Vertaal UML datatype “Real”  naar xs:double en UML datatype “Decimal” naar xs:decimal 
Bijlage 1 Voorstel voor definities voor primaire datatypen van getallen  in MIM
--_

Decimal ontbrak in MIM. Suggestie leek gewekt te worden dat een Decimal een Real is met een Restrictie, maar een Real is anders bedoeld. Hoewel beide reëele getallen zijn, zijn ze echt anders van aard (ze staan ze niet in dezelfde verhouding als bijvoorbeeld Integer en NonNegativeInteger). verder, Real wordt bijna niet gebruikt in informatiemodellen en Decimal juist wel. 

Dus, voorstel is om Decimal toe te voegen en even goed te kijken naar de definitie van Real en naar tekst waarin Decimal en Real bij elkaar genoemd worden, om ze goed uit elkaar te trekken. 

Voorstel Peter Lentjes door de definities: 

Definitie Real
Zie ISO11404 (subtype van ISO Number). 
Real is een familie van datatypes, waarvan elk datatype een computationele benadering is van “reële getallen”. Reële getallen behoren tot de wiskundige verzameling van gehele getalen (integers), rationale getallen (breuken) en andere exacte getallen, zoals π (pi) en √2. Reële getallen die in een decimale representatie een oneindig aantal cijfers achter de komma hebben, zoals 1/3 en √2, kunnen in een computersysteem nooit exact worden vastgelegd. Maar met een Real datatype kunnen deze getallen wel vastgelegd worden, echter met een beperkte precisie. Een Real wordt daarom vaak ook floating-point datatype genoemd. De mate van precisie bepaalt uit hoeveel cijfers het getal maximaal mag bestaan bij een bepaalde nauwkeurigheid. Als een Real getal een precisie heeft van 64 bits, dan worden alleen de eerste 15-16 cijfers nauwkeurig opgeslagen. Als je bijv. het getal 18100.56 opstaat in de computer en je vraagt het daarna op met 12 cijfers achter de komma (totaal 17 cijfers) dan zou het resultaat er als volgt uit kunnen zien:  18100.560000000017, dus niet meer exact dezelfde waarde.

Definitie Decimal
Decimal is een datatype maarmee een reëel getal exact kan worden opgeslagen in een computer. Zie ook de definitie van Real. Dat wil zeggen dat als je het getal 18100.56 opslaat als Decimal en je vraagt het daarna op met 14 cijfers achter de komma, je nog steeds de exacte waarde terug krijgt, namelijk 18100.56000000000000.  Een compiuter kan echter geen oneindig hoge precisie realiseren., dus in de praktijk is een decimal een getal met een heel hoge  precisie.

Definitie Integer
Integer is een datatype waarmee een geheel getal exact kan worden opgeslagen. Integer is een subtype van rationaal getal (breuk of ratio van 2 gehele getallen)  waarbij de noemer de waarde 1 heeft, bijv. 2347 = 2347/1.

**Comment by dkrijtenburg-GNM** [comment]
Linda : verder uitzoeken of er een internationale standaard voor DECIMAL is.

**Comment by dkrijtenburg-GNM** [comment]
Linda: Heb je ook eren betere definitie voor REAL?

**Comment by GeraldGrootRoessink** [comment]
Voor een Linked Data representatie van een model met SHACL wordt expliciet gebruik gemaakt van de XSD:datatypen. Ik pleit er voor om de MIM-primitieven te kiezen waarmee je een round-trip kunt maken via een shacl model. 

Overingen er zijn in de XSD meer datatypen dan de de primitives die je bijvoorbeeld in JAVA tegenkomt. In de praktijk is slechts een deel van XSD bruikbaar.

**Comment by GeraldGrootRoessink** [comment]
Ik zie al een uitwerking hiervan in #72

**Comment by PalmJanssen** [comment]
Refereer aan ISO 19103 en pas dat toe in MIM.
Bijvoorbeeld:

![image](https://user-images.githubusercontent.com/9932784/64332290-91f0bb00-cfd4-11e9-979e-68edbb0cb1dd.png)




DECIMAL:
7.2.6.1 Semantics
Decimal (see Figure 9) is a decimal data type in which the number represents an exact value, as a finite representation of a decimal number. It differs from the common binary real implementation in that it can represent 1/10 (one-tenth) without error, while binary real representation can only represent powers of exactly 1/2 (one-half). Since many currencies are decimal, these representations are preferred in dealing with such values. This is also true for mile markers, which are often given in decimals.
NOTE This differs from real, as real is an approximate value and Decimal is exact.

REAL:
7.2.8 Real
7.2.8.1 Semantics
Real (see Figure 9) is a signed real (floating point) number consisting of a mantissa and an exponent, which represents a value to a precision given by the number of digits shown, but is not necessarily the exact value. The length of a real is encapsulation and usage dependent. The common binary real implementation uses base 2. Since such real numbers can approximate any measure where absolute accuracy is not possible, this form of numeric is most often used for measures. In cases were absolute accuracy is needed, such as currencies, then a decimal representation may be preferred (assuming the currency is decimal, such as the U.S. dollar or British pound). Where there are no subunits possible, integer numbers may be preferred. A real can be considered as an integer part followed by a fractional part given in multiples of powers of 1/2 (halves). See ISO/IEC 11404, 8.1.10 for further description.

**Comment by dkrijtenburg-GNM** [comment]
kan verwerkt worden in Respec
